move_group:
  ros__parameters:
    # These publish_* booleans control how often the PlanningScene is updated in RViz, etc.
    planning_scene_monitor:
      publish_geometry_updates: true
      publish_state_updates: true
      publish_transforms_updates: true

      # The occupancy_map_monitor section is where the 3D sensor plugin(s) must be defined.
      occupancy_map_monitor:
        plugins:
          # You can name this plugin “point_cloud_updater” or whatever you like
          - name: point_cloud_updater
            type: occupancy_map_monitor/PointCloudOctomapUpdater
            # Make sure the point_cloud_topic matches the actual point cloud topic you have
            point_cloud_topic: "/camera_depth/points"
            max_range: 3.0
            point_subsample: 1
            point_cloud_frame: "camera_link"
            monitored_frame: "base_link"
