# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    panda_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - j1
      - j2
      - j3
      - j4
      - j5
      - j6
    allow_nonzero_velocity_at_trajectory_end: true
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      j1: { trajectory: 0.2, goal: 0.1 }
      j2: { trajectory: 0.2, goal: 0.1 }
      j3: { trajectory: 0.2, goal: 0.1 }
      j4: { trajectory: 0.2, goal: 0.1 }
      j5: { trajectory: 0.2, goal: 0.1 }
      j6: { trajectory: 0.2, goal: 0.1 }
